services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5000:5000"

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5001:5001"
